-- TrendRadar PostgreSQL 初始化脚本
-- 创建中文全文检索所需扩展和 news_articles 表

CREATE EXTENSION IF NOT EXISTS zhparser;

-- 使用 zhparser 作为中文分词器
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_ts_config WHERE cfgname = 'chinese'
    ) THEN
        CREATE TEXT SEARCH CONFIGURATION chinese (PARSER = zhparser);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_ts_config cfg
        JOIN pg_ts_config_map map ON map.mapcfg = cfg.oid
        JOIN pg_ts_parser prs ON prs.oid = cfg.cfgparser
        JOIN ts_token_type(prs.oid) tok ON tok.tokid = map.maptokentype
        WHERE cfg.cfgname = 'chinese'
          AND tok.alias IN ('n', 'v', 'a', 'i', 'e', 'l')
    ) THEN
        ALTER TEXT SEARCH CONFIGURATION chinese ADD MAPPING FOR n,v,a,i,e,l WITH simple;
    END IF;
END $$;

-- 平台信息表
CREATE TABLE IF NOT EXISTS platforms (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    is_active INTEGER DEFAULT 1,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 新闻条目表
CREATE TABLE IF NOT EXISTS news_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    platform_id TEXT NOT NULL,
    rank INTEGER NOT NULL,
    url TEXT DEFAULT '',
    mobile_url TEXT DEFAULT '',
    first_crawl_time TEXT NOT NULL,
    last_crawl_time TEXT NOT NULL,
    crawl_count INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (platform_id) REFERENCES platforms(id)
);

-- 标题变更历史表
CREATE TABLE IF NOT EXISTS title_changes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_item_id INTEGER NOT NULL,
    old_title TEXT NOT NULL,
    new_title TEXT NOT NULL,
    changed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (news_item_id) REFERENCES news_items(id)
);

-- 排名历史表
CREATE TABLE IF NOT EXISTS rank_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_item_id INTEGER NOT NULL,
    rank INTEGER NOT NULL,
    crawl_time TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (news_item_id) REFERENCES news_items(id)
);

-- 抓取记录表
CREATE TABLE IF NOT EXISTS crawl_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crawl_time TEXT NOT NULL UNIQUE,
    total_items INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 抓取来源状态表
CREATE TABLE IF NOT EXISTS crawl_source_status (
    crawl_record_id INTEGER NOT NULL,
    platform_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('success', 'failed')),
    PRIMARY KEY (crawl_record_id, platform_id),
    FOREIGN KEY (crawl_record_id) REFERENCES crawl_records(id),
    FOREIGN KEY (platform_id) REFERENCES platforms(id)
);

-- 时间段执行记录表
CREATE TABLE IF NOT EXISTS period_executions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_date TEXT NOT NULL,
    period_key TEXT NOT NULL,
    action TEXT NOT NULL,
    executed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(execution_date, period_key, action)
);

-- RSS 源配置表
CREATE TABLE IF NOT EXISTS rss_feeds (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    feed_url TEXT DEFAULT '',
    is_active INTEGER DEFAULT 1,
    last_fetch_time TEXT,
    last_fetch_status TEXT,
    item_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- RSS 条目表
CREATE TABLE IF NOT EXISTS rss_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    feed_id TEXT NOT NULL,
    url TEXT NOT NULL,
    published_at TEXT,
    summary TEXT,
    author TEXT,
    first_crawl_time TEXT NOT NULL,
    last_crawl_time TEXT NOT NULL,
    crawl_count INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (feed_id) REFERENCES rss_feeds(id)
);

-- RSS 抓取记录表
CREATE TABLE IF NOT EXISTS rss_crawl_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crawl_time TEXT NOT NULL UNIQUE,
    total_items INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- RSS 抓取来源状态表
CREATE TABLE IF NOT EXISTS rss_crawl_status (
    crawl_record_id INTEGER NOT NULL,
    feed_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('success', 'failed')),
    error_message TEXT,
    PRIMARY KEY (crawl_record_id, feed_id),
    FOREIGN KEY (crawl_record_id) REFERENCES rss_crawl_records(id),
    FOREIGN KEY (feed_id) REFERENCES rss_feeds(id)
);

-- RSS 推送记录表
CREATE TABLE IF NOT EXISTS rss_push_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL UNIQUE,
    pushed INTEGER DEFAULT 0,
    push_time TEXT,
    ai_analyzed INTEGER DEFAULT 0,
    ai_analysis_time TEXT,
    ai_analysis_mode TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
-- 新闻文章表
CREATE TABLE IF NOT EXISTS news_articles (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    source_name TEXT NOT NULL DEFAULT '',
    source_url TEXT NOT NULL DEFAULT '',
    published_at TIMESTAMP WITH TIME ZONE,
    category_l1 TEXT NOT NULL DEFAULT '',
    category_l2 TEXT NOT NULL DEFAULT '',
    keywords TEXT[] NOT NULL DEFAULT '{}',
    crawl_count INTEGER NOT NULL DEFAULT 1,
    crawl_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 长标题会超过 PostgreSQL btree 单行索引限制，改用 md5(title) 去重
DROP INDEX IF EXISTS idx_news_articles_title;
CREATE UNIQUE INDEX IF NOT EXISTS idx_news_articles_title_md5 ON news_articles (md5(title));

-- 中文全文检索索引（zhparser 分词）
CREATE INDEX IF NOT EXISTS idx_news_articles_title_fts ON news_articles
    USING GIN (to_tsvector('chinese', title));

-- 关键词数组索引（用于关键词筛选）
CREATE INDEX IF NOT EXISTS idx_news_articles_keywords ON news_articles USING GIN (keywords);

-- 发布时间索引（用于日期筛选和排序）
CREATE INDEX IF NOT EXISTS idx_news_articles_published_at ON news_articles (published_at DESC);

-- 抓取时间索引
CREATE INDEX IF NOT EXISTS idx_news_articles_crawl_time ON news_articles (crawl_time DESC);

-- 一级分类索引
CREATE INDEX IF NOT EXISTS idx_news_articles_category_l1 ON news_articles (category_l1);

-- 复合索引：关键词 + 发布日期
CREATE INDEX IF NOT EXISTS idx_news_articles_keywords_date ON news_articles
    USING GIN (keywords) WHERE published_at IS NOT NULL;

-- 平台索引
CREATE INDEX IF NOT EXISTS idx_news_platform ON news_items(platform_id);

-- 新闻时间索引
CREATE INDEX IF NOT EXISTS idx_news_crawl_time ON news_items(last_crawl_time);

-- 新闻标题索引
CREATE INDEX IF NOT EXISTS idx_news_title ON news_items(title);

-- URL + platform_id 唯一索引（仅对非空 URL 生效）
CREATE UNIQUE INDEX IF NOT EXISTS idx_news_url_platform
    ON news_items(url, platform_id) WHERE url <> '';

-- 抓取状态索引
CREATE INDEX IF NOT EXISTS idx_crawl_status_record ON crawl_source_status(crawl_record_id);

-- 排名历史索引
CREATE INDEX IF NOT EXISTS idx_rank_history_news ON rank_history(news_item_id);

-- 时间段执行记录索引
CREATE INDEX IF NOT EXISTS idx_period_exec_lookup
    ON period_executions(execution_date, period_key, action);

-- RSS 源索引
CREATE INDEX IF NOT EXISTS idx_rss_feed ON rss_items(feed_id);

-- RSS 发布时间索引
CREATE INDEX IF NOT EXISTS idx_rss_published ON rss_items(published_at DESC);

-- RSS 抓取时间索引
CREATE INDEX IF NOT EXISTS idx_rss_crawl_time ON rss_items(last_crawl_time);

-- RSS 标题索引
CREATE INDEX IF NOT EXISTS idx_rss_title ON rss_items(title);

-- URL + feed_id 唯一索引
CREATE UNIQUE INDEX IF NOT EXISTS idx_rss_url_feed
    ON rss_items(url, feed_id);

-- RSS 抓取状态索引
CREATE INDEX IF NOT EXISTS idx_rss_crawl_status_record ON rss_crawl_status(crawl_record_id);

-- 迁移：为已有表添加 crawl_count 列
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'news_articles'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'news_articles' AND column_name = 'crawl_count'
    ) THEN
        ALTER TABLE news_articles ADD COLUMN crawl_count INTEGER NOT NULL DEFAULT 1;
    END IF;
END $$;
